#import "template.typ": template
#import "@rheo/rookery:0.4.1": idea, window

#set document(title: [Authors])
#show: template.with(current-page: "authors")

#let author(tags: (), ..args) = idea(tags: ("author",) + tags, ..args)

#author(<herbert-mehrtens>, title: [Herbert Mehrtens])[]
#author(<jeremy-gray>, title: [Jeremy Gray])[]
#author(<sarah-pourciau>, title: [Sarah Pourciau])[]
#author(<aaron-scott>, title: [Scott Aaronson])[]
#author(<atiyah-michael>, title: [Michael Atiyah])[]
#author(<avigad-jeremy>, title: [Jeremy Avigad])[]
#author(<babbage-charles>, title: [Charles Babbage])[]
#author(<benacerraf-paul>, title: [Paul Benacerraf])[]
#author(<berkeley-george>, title: [George Berkeley])[]
#author(<castelle-michael>, title: [Michael Castelle])[]
#author(<deringer-william>, title: [William Deringer])[]
#author(<henkle-jonah>, title: [Jonah Henkle])[]
#author(<horl-erich>, title: [Erich Hörl])[]
#author(<husserl-edmund>, title: [Edmund Husserl])[]
#author(<joque-justin>, title: [Justin Joque])[]
#author(<krieger-martin>, title: [Martin Krieger])[]
#author(<longo-giuseppe>, title: [Giuseppe Longo])[]
#author(<marx-george>, title: [George Marx])[]
#author(<marx-karl>, title: [Karl Marx])[]
#author(<mazzotti-massimo>, title: [Massimo Mazzotti])[]
#author(<meli-domenico>, title: [Domenico Meli])[]
#author(<miller-jacques>, title: [Jacques Miller])[]
#author(<naderi-reza>, title: [Reza Naderi])[]
#author(<peirce-charles>, title: [Charles Peirce])[]
#author(<poincare-henri>, title: [Henri Poincaré])[]
#author(<rodin-andrei>, title: [Andrei Rodin])[]
#author(<ruda-frank>, title: [Frank Ruda])[]
#author(<schmid-eric>, title: [Eric Schmid])[]
#author(<serres-michel>, title: [Michel Serres])[]
#author(<siegert-bernhard>, title: [Bernhard Siegert])[]
#author(<weatherby-leif>, title: [Leif Weatherby])[]
#author(<vasilie-na-a>, title: [N. A. Vasiliev])[]
#author(<vonfoerster-heinz>, title: [Heinz Von Foerster])[]
#author(<vonneumann-john>, title: [John von Neumann])[]
#author(<warwick-andrew>, title: [Andrew Warwick])[]
#author(<thurston-william>, title: [William P. Thurston])[]
#author(<turing-alan>, title: [Alan Turing])[]
#author(<steingart-alma>, title: [Alma Steingart])[]
#author(<bernoulli-daniel>, title: [Daniel Bernoulli])[]
#author(<bernoulli-johann>, title: [Johann Bernoulli])[]
#author(<jing-felicia>, title: [Felicia Jing])[]
